version: "2"

services:

  client-docker:
    image: dorowu/ubuntu-desktop-lxde-vnc:release-v1.1
    container_name: client-docker
    ports:
     - "6080:6080"
    links:
     - idp:idp-docker
     - rest:rest-docker
  
  idp:
    build: ./idp
    container_name: idp
    links:
     - ldap:ldap-docker
     - rest:rest-docker

  ldap:
    image: greggigon/apacheds
    container_name: ldap
    ports:
     - "10389:10389"
    volumes:
     - ./ldap/bootstrap/:/bootstrap
    environment:
     - BOOTSTRAP_FILE=/bootstrap/users.ldif
  rest:
    build: ./rest
    container_name: rest
    ports:
     - "8080:8080"
     - "8443:8443"
    volumes:
     - ./idp/shibboleth-idp/metadata/idp-metadata.xml:/root/rest/saml/security/idp-metadata.xml
