version: "2"

services:

  client-docker:
    image: docker.local:5000/dorowu-ubuntu-desktop-lxde-vnc
    ports:
     - "6080:6080"
    links:
     - idp:idp-docker
     - rest:rest-docker
  
  idp:
    build: ./idp
    links:
     - ldap:ldap-docker
     - rest:rest-docker

  ldap:
    image: docker.local:5000/greggigon-apacheds
    ports:
     - "10389:10389"
    volumes:
     - ./ldap/bootstrap/:/bootstrap
    environment:
     - BOOTSTRAP_FILE=/bootstrap/users.ldif
  rest:
    build: ./rest
    ports:
     - "8080:8080"
     - "8443:8443"
    volumes:
     - ./idp/shibboleth-idp/metadata/idp-metadata.xml:/root/rest/saml/security/idp-metadata.xml
