version: '2'
services:
  pgsql:
    image: postgres
    hostname: "pgsql"
    container_name:
      "pgsql"
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=password
  rest:
    image: 10.62.87.31:5000/restapi/ubuntu/stateless/restapi
    ports:
      - "8080:8080"
      - "9443:8443"
    container_name: rest
    hostname: rest
    volumes: 
      - ./rest/config:/root/rest/config
      - ./rest/logs:/root/rest/logs
    links:
      - centstateless
    depends_on:
      - centstateless
  centstateless:
    image: 10.62.87.31:5000/contentserver_centos
    environment:
      - HIGH_VOLUME_SERVER_LICENSE=
      - TRUSTED_LICNESE=
      - STORAGEAWARE_LICENSE=
      - XMLSTORE_LICENSE=
      - SNAPLOCKSTORE_LICENSE=LDNAPJEWPXQ
      - RPS_LICENSE=
      - FED_RECD_SERVICE_LICENSE=
      - RECORD_MANAGER_LICENSE=
      - PRM_LICENSE=
      - ROOT_USER_PASSWORD=${ROOT_USER_PASSWORD}
      - INSTALL_OWNER_PASSWORD=${INSTALL_OWNER_PASSWORD}
      - INSTALL_OWNER_USER=dmadmin
      - REPOSITORY_PASSWORD=${REPOSITORY_PASSWORD}
      - EXTERNAL_IP=10.62.87.29
      - EXTERNALDB_IP=pgsql
      - EXTERNALDB_ADMIN_USER=postgres
      - EXTERNALDB_ADMIN_PASSWORD=${EXTERNALDB_ADMIN_PASSWORD}
      - DB_SERVER_PORT=5432
      - DOCBASE_ID=45321
      - DOCBASE_NAME=centdb
      - USE_EXISTING_DATABASE_ACCOUNT=false
      - INDEXSPACE_NAME=dm_repo_docbase
      - BOF_REGISTRY_USER_PASSWORD=${BOF_REGISTRY_USER_PASSWORD}
      - AEK_ALGORITHM=AES_256_CBC
      - AEK_PASSPHRASE=${AEK_PASSPHRASE}
      - AEK_NAME=CSaek
      - ENABLE_LOCKBOX=true
      - LOCKBOX_FILE_NAME=lockbox.lb
      - LOCKBOX_PASSPHRASE=${LOCKBOX_PASSPHRASE}
      - USE_EXISTING_AEK_LOCKBOX=false
      - CONFIGURE_THUMBNAIL_SERVER=NO
      - EXTDOCBROKERPORT=1689
      - CONTENTSERVER_PORT=50000
      - APP_SERVER_ADMIN_PASSWORD=${APP_SERVER_ADMIN_PASSWORD}
      - INSTALL_OWNER_UID=
    hostname:
      "centstateless"
    container_name:
      "centstateless"
    ports:
     - "1689:1689"
     - "1690:1690"
     - "50000:50000"
     - "50001:50001"
     - "9080:9080"
     - "9082:9082"
     - "9081:9081"
     - "8081:8081"
     - "8443:8443"
     - "9084:9084"
    volumes:
     - centdb_odbc:/opt/dctm/odbc
     - centdb_data:/opt/dctm/data
     - centdb_dba:/opt/dctm/dba
     - centdb_share:/opt/dctm/share
     - centdb_dfc:/opt/dctm/config
     - centdb_xhive_storage:/opt/dctm/xhive_storage
     - centdb_XhiveConnector:/opt/dctm/wildfly9.0.1/server/DctmServer_MethodServer/deployments/XhiveConnector.ear
     - centdb_mdserver_conf:/opt/dctm/mdserver_conf
     - centdb_mdserver_log:/opt/dctm/wildfly9.0.1/server/DctmServer_MethodServer/log
     - centdb_mdserver_logs:/opt/dctm/wildfly9.0.1/server/DctmServer_MethodServer/logs
     - centdb_Thumbnail_Server_conf:/opt/dctm/product/7.3/thumbsrv/conf
     - centdb_Thumbnail_Server_webinf:/opt/dctm/product/7.3/thumbsrv/container/webapps/thumbsrv/WEB-INF
    privileged: true
  primary: 
    image: 10.8.46.202:5000/xplore/ubuntu/stateless/xplore:1.6.0000.0835
    hostname: primary
    container_name: primary
    ports:
      - "9300:9300"
    volumes:
      - xplore:/root/xPlore/rtdata
    depends_on:
      - centstateless
  cps:
    image: 10.8.46.202:5000/xplore/ubuntu/stateless/xplore:1.6.0000.0835
    hostname: cps
    container_name: cps
    environment:
      - role=cps
      - primary_addr=primary
    depends_on:
      - primary
  indexagent:
    image: 10.8.46.202:5000/indexagent/ubuntu/stateless/indexagent:1.6.0000.0835
    hostname: indexagent
    container_name: indexagent
    ports:
      - "9200:9200"
    environment:
      - primary_addr=primary
      - docbase_name=centdb
      - docbase_user=dmadmin
      - docbase_password=password
      - broker_host=centstateless
      - broker_port=1489
      - registry_name=centdb
      - registry_user=dm_bof_registry
      - registry_password=password
    depends_on:
      - primary
    volumes_from:
      - primary
volumes:
 xplore: {}
 centdb_data:
    driver: local
 
 centdb_dba:
 centdb_share:
    driver: local
 
 centdb_dfc:
 centdb_odbc:
 centdb_XhiveConnector:
 centdb_mdserver_conf:
 centdb_mdserver_log:
 centdb_mdserver_logs:
 centdb_Thumbnail_Server_conf:
 centdb_Thumbnail_Server_webinf:
 centdb_xhive_storage: